= Платформа
:doctype: article

== Цель
Цель разработки платформы - предоставление удобного инструментария для пользователей, авторов и разработчиков.

Удобство пользователей:: автообновление по сети. Больше не нужно скачивать и устанавливать новую версию плеера. Все истории можно найти в единой библиотеке прямо из плеера. Новый функционал появляется сразу по мере выхода.

Удобство авторов:: автообновление по сети. Больше не нужно скачивать и устанавливать новую версию редактора. Историю можно опубликовать в библиотеке прямо из редактора. Редактор проверит и протестирует историю. Новый функционал появляется сразу по мере выхода.

Удобство разработчиков:: возможность разработки модулей независимо друг от друга. Возможность интеграционного тестирование модулей на на специальной платформе с диагностическими модулями. Оперативная доставка новых модулей, исправлений до клиентов.

Платформа представляет собой клиент-серверный программный комплекс, состоящий из сервера (как минимум один) и клиента (как минимум один). Сервер содержит в себе:

- репозиторий модулей, используемый для обновления клиентов;
- библиотеку, с интерактивными историями;
- API _надо подумать_;
- сайт проекта.

Клиенты, в зависимости от набора используемых модулей могут быть представлены проигрывателем историй и/или редактором историй. Во втором случае клиент содержит значительно большее количество модулей.

Типичный клиент-проигрыватель включает в себя следующие модули:

- система хранения историй;
- система хранения сохранений;
- хранитель AST дерева;
- виртуальная машина;
- парсер ввода;
- синтаксический анализатор;
- словарь слов (перекрывается словарём истории);
- библиотека стандартных реакций (перекрывается библиотекой истории);
- система вывода текста.

Так же могут быть включены:

- система вывода изображений;
- система вывода звука.

Редактор содержит все те же подсистемы, и, в дополнение к ним:

- мастер изменения AST дерева через формы;

Также могут быть включены:

- мастер изменения AST дерева псевдокодем;
- мастер изменения AST дерева литературным кодом;
- верификатор AST дерева;
- отладчик истории;
- тестер истории.

== Функционал
После запуска платформы выполняется конфигурирование модулей в соответствии с настройками в конфигурационных файлах. Если запущен сервер, то он переходит в режим ожидания соединений, иначе выполняется поиск обновлений на сервере в интернете (при разрешённых настройках).

Плеер загружает модули, необходимые для проигрывания истории, а также загружает описание историй из каталога библиотеки. Если в командной строке была указана история, то она загружается в плеер. Если в командной строке ничего не было указано, то отображается библиотека, где пользователь может выбрать историю, которая будет загружена из интернета или

Редактор загружает модули для редактирования, тестирования и воспроизведения. Если в командной строке была указана история, то она загружается в редактор.

== Детали реализации
Ниже представлены основные технические моменты реализации платформы.

=== Интерактивная история
Интерактивная история представляет собой упакованный контейнер (ZIP файл), содержащий специальную META информацию, файл с историей и дополнительные файлы, которые требуются игре или системе:

[plantuml, format="svg", title="Структура истории"]
----
title
example.ifz
|_ .meta.xml
|_ story.xml
|_ assets
|_ images
  |_ image_1.jpg
  |_ image_2.jpg
|_ sounds
  |_ sound_1.mp3
  |_ sound_2.mp3
end title
----
Необходимыми являются файлы `.meta.xml` и `story.xml` (хотя этот файл может называться по-другому). `.meta.xml` хранит описание истории, аннотацию и картинку для библиотеки, ссылку на автора. Если история разделена на несколько томов (*.ifz, *.if1, *.if2, ...), то в файле также указан перечень томов, подлежащих загрузке.

=== Платформа
Платформа строится на фреймворке, реализующем стандарт OSGi 6.0.0, -- Apache Felix. Стандарт предусматривает управление зависимостями в виде "Регистра сервисов":

[plantuml, format="svg", title="Регистр сервисов"]
----
"Модуль А" -up->[Регистрирует сервис] "Реестр"
"Модуль Б" -up->[Ищет сервис] "Реестр"
"Модуль Б" -left->[Вызов сервиса] "Модуль А"
----

Каждый модуль представляет из себя JAR файл, оформленный особым образом (bundle).
Модуль имеет собственный жизненный цикл и точку входа в модуль.

[plantuml, format="svg", title="Жизненный цикл модуля"]
----
(*) --> "Загружен"
"Загружен" --> "Подготовлен"
"Подготовлен" --> "Выгружен"
"Выгружен" --> (*)
"Подготовлен" -right->[Запуск] "Запускается"
"Запускается" --> "Работает"
"Работает" -down->[Останов] "Останавливается"
"Останавливается" --> "Подготовлен"
----

Точка входа представляет собой реализацию интерфейса `BundleActivator`:
[source, lang="java"]
----
public class Activator implements BundleActivator {

    public void start(BundleContext context) {
        // ... action for start module ...
    }

    public void stop(BundleContext context) {
        // ... action for stop module ...
    }

}
----

Метод `start` выполняется при запуске модуля, а метод `stop` при его остановке.
