= Платформа
:doctype: article

== Цель
Цель разработки платформы - предоставление удобного инструментария для пользователей, авторов и разработчиков.

Удобство пользователей:: автообновление по сети. Больше не нужно скачивать и устанавливать новую версию плеера. Все истории можно найти в единой библиотеке прямо из плеера. Новый функционал появляется сразу по мере выхода.

Удобство авторов:: автообновление по сети. Больше не нужно скачивать и устанавливать новую версию редактора. Историю можно опубликовать в библиотеке прямо из редактора. Редактор проверит и протестирует историю. Новый функционал появляется сразу по мере выхода.

Удобство разработчиков:: возможность разработки модулей независимо друг от друга. Возможность интеграционного тестирование модулей на на специальной платформе с диагностическими модулями. Оперативная доставка новых модулей, исправлений до клиентов.

Платформа представляет собой клиент-серверный программный комплекс, состоящий из сервера (как минимум один) и клиента (как минимум один). Сервер содержит в себе:

- репозиторий модулей, используемый для обновления клиентов;
- библиотеку, с интерактивными историями;
- API _надо подумать_;
- сайт проекта.

Клиенты, в зависимости от набора используемых модулей могут быть представлены проигрывателем историй и/или редактором историй. Во втором случае клиент содержит значительно большее количество модулей.

Типичный клиент-проигрыватель включает в себя следующие модули:

- система хранения историй;
- система хранения сохранений;
- хранитель AST дерева;
- виртуальная машина;
- парсер ввода;
- синтаксический анализатор;
- словарь слов (перекрывается словарем истории);
- библиотека стандартных реакций (перекрывается библиотекой истории);
- система вывода текста.

Так же могут быть включены:

- система вывода изображений;
- система вывода звука.

Редактор содержит все те же подсистемы, и, в дополнение к ним:

- мастер изменения AST дерева через формы;

Также могут быть включены:

- мастер изменения AST дерева псевдокодем;
- мастер изменения AST дерева литературным кодом;
- верификатор AST дерева;
- отладчик истории;
- тестер истории.
