package ifml2.editor.gui.forms.expressions;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class TextExpressionEditForm extends ExpressionEditForm {
    private final String textLiteralRegEx = "'([^']*)'";
    private Pattern pattern = Pattern.compile(textLiteralRegEx);
    private JPanel contentPane;
    private JRadioButton textRadioButton;
    private JRadioButton expressionRadioButton;
    private JTextArea textTextArea;
    private JTextArea expressionTextArea;

    public TextExpressionEditForm(String expression) {
        super(expression);
        setContentPane(contentPane);

        textRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                textTextArea.setEnabled(e.getStateChange() == ItemEvent.SELECTED);
            }
        });
        expressionRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                expressionTextArea.setEnabled(e.getStateChange() == ItemEvent.SELECTED);
            }
        });

        bindData();
    }

    @Override
    protected void bindData() {
        expressionTextArea.setText(expression);

        if (expression == null || pattern.matcher(expression).matches()) {
            textTextArea.setText(expression != null ? extractText(expression) : "");
            textRadioButton.setSelected(true);
        } else {
            expressionRadioButton.setSelected(true);
        }
    }

    @Override
    public String getEditedExpression() {
        return textRadioButton.isSelected() ? createLiteral(textTextArea.getText()) : expressionTextArea.getText();
    }

    private String createLiteral(String text) {
        return "'" + text + "'";
    }

    private String extractText(String expression) {
        Matcher matcher = pattern.matcher(expression);
        return matcher.matches() ? matcher.group(1) : "";
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 2, new Insets(4, 4, 4, 4), -1, -1));
        textRadioButton = new JRadioButton();
        textRadioButton.setText("Текст:");
        textRadioButton.setMnemonic('Т');
        textRadioButton.setDisplayedMnemonicIndex(0);
        contentPane.add(textRadioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        expressionRadioButton = new JRadioButton();
        expressionRadioButton.setText("Выражение:");
        expressionRadioButton.setMnemonic('В');
        expressionRadioButton.setDisplayedMnemonicIndex(0);
        contentPane.add(expressionRadioButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 100), null, 0, false));
        textTextArea = new JTextArea();
        textTextArea.setEnabled(false);
        textTextArea.setLineWrap(true);
        textTextArea.setWrapStyleWord(true);
        scrollPane1.setViewportView(textTextArea);
        final JScrollPane scrollPane2 = new JScrollPane();
        contentPane.add(scrollPane2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 100), null, 0, false));
        expressionTextArea = new JTextArea();
        expressionTextArea.setEnabled(false);
        expressionTextArea.setLineWrap(true);
        expressionTextArea.setWrapStyleWord(true);
        scrollPane2.setViewportView(expressionTextArea);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(textRadioButton);
        buttonGroup.add(expressionRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}