package ifml2.editor.gui.forms.expressions;

import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.GlazedLists;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ifml2.editor.gui.forms.ListEditForm;
import ifml2.om.IFMLObject;
import ifml2.om.Item;
import ifml2.om.Story;
import ifml2.om.Word;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;
import java.util.Collection;
import java.util.Iterator;

public class CollectionEditForm extends JInternalFrame {
    private final EventList<IFMLObject> editedCollection;
    private JPanel contentPane;
    private ListEditForm<IFMLObject> collectionListEditForm;
    private Window owner;
    private Class<? extends IFMLObject> filterByClass;
    private Story.DataHelper dataHelper;
    private Item holder;

    public CollectionEditForm(Window owner, @NotNull EventList<IFMLObject> collectionItems, Class<? extends IFMLObject> filterByClass,
                              @NotNull Item holder, Story.DataHelper dataHelper) {
        this.owner = owner;
        this.filterByClass = filterByClass;
        this.dataHelper = dataHelper;
        this.holder = holder;
        $$$setupUI$$$();
        setContentPane(contentPane);

        editedCollection = GlazedLists.eventList(collectionItems);

        collectionListEditForm.bindData(editedCollection);
    }

    private void createUIComponents() {
        collectionListEditForm = new ListEditForm<IFMLObject>(owner, "элемент", "элемента", Word.Gender.MASCULINE, IFMLObject.class) {
            {
                setShowEditButton(false);
            }

            @Override
            protected IFMLObject createElement() throws Exception {
                final Collection<IFMLObject> allObjects = dataHelper.getCopyOfAllObjects();

                // filter objects by type and presence in collection
                for (Iterator<IFMLObject> iterator = allObjects.iterator(); iterator.hasNext(); ) {
                    IFMLObject object = iterator.next();
                    if (!filterByClass.isInstance(object) || getClonedList().contains(object) || holder.equals(object)) {
                        iterator.remove();
                    }
                }

                if (!allObjects.isEmpty()) {
                    return (IFMLObject) JOptionPane.showInputDialog(owner, "Выберите объект для добавления", "Новый элемент коллекции",
                            JOptionPane.QUESTION_MESSAGE, null, allObjects.toArray(), null);
                } else {
                    JOptionPane
                            .showMessageDialog(owner, "Не осталось предметов для добавления", "Нет предметов", JOptionPane.WARNING_MESSAGE);
                    return null;
                }
            }


        };
    }

    public EventList<IFMLObject> getEditedCollection() {
        return editedCollection;
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(4, 4, 4, 4), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.add(collectionListEditForm.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
