The Roadmap
===========
:doctype: article
:icons: font

== Конфигурация

[WARNING]
====
Этот раздел требует обсуждения!
====

Необходимо сохранять некоторые настройки между запусками программы. Например, последнюю выбранную папку,  последнюю сохранённую игру и т.п. ...

Обычно, программы сохраняют специфичные им настройки в определённой папке. Сейчас большинство программ делает это в _Unix_ стиле -- `${user.home}/.ifml2`
Внутри этой папки можно располагать любые данные программы без опасения, что они будут повреждены (если только пользователь не удалит данную папку.
Например, можно хранить конфигурацию `ifml2.conf`, папку для плагинов и обновлений `bundles`, кеш -- `cache`, стандартную библиотеку глаголов и т.п.

== Реструктуризация

[WARNING]
====
Этот раздел требует обсуждения!
====

В текущем состоянии в проекте существует сильная связанность между компонентами. При изменении какой либо части -- последствия могут проявится в других частях проекта. Требуется разделение на слабосвязанные компоненты.

== Грамматика (Синтаксический анализатор)

[WARNING]
====
Этот раздел требует обсуждения!
====

В текущей реализации приложения используется стандартная библиотека глаголов, для описания базовых действий, поддерживаемых системой. Если автору необходимо добавить своё действие или объект, то ему нужно записать все возможные формы слова (склонения/спряжения), чтобы парсер смог это слово опознать. Это достаточно рутинная и трудоёмкая работа, от которой хотелось бы оградить автора. С этой целью вводится модуль `grammar`, задачей которого является предварительный семантический разбор вводимой фразы, выделение лексической информации и выдача её в удобном для автора виде. На текущий момент API представляет собой следующее:

[source]
--
object Grammar {
    fun parse(sentence: String): List<List<Word>>
}
--

`Word` -- представляет из себя интерфейс с единственным параметром:

[source]
--
interface Word {
    val name: String
}
--

Простейшая реализация этого интерфейса:

[source]
--
data class Unknown(override val name: String)
--

предназначена для слов, которые не могут быть распознаны синтаксическим анализатором. Всего возможны следующие виды:

* Unknown -- нераспознанное
* Noun -- существительное
* Verb -- глагол
* Particle -- частица
* Union -- союз

== Редактор кода

[WARNING]
====
Этот раздел требует обсуждения!
====

Многие авторы имеют некоторое отношение к программированию. Для них быстрее и удобнее описать сцену на некотором языке программирования, чем делать всё это 
в виде настроек по окошкам и формам. Для таких авторов можно создать редактор кода, однозначно отображающегося на `xml`. Таким образом была бы возможность писать одну историю и в виде кода и в виде настроек и окошек в редакторе.

== Текстовый конструктор

[WARNING]
====
Этот раздел требует обсуждения!
====

По мере развития семантического анализатора естественного языка станет возможным использовать его не только в парсере для анализа вводимых комманд, но и в процессе создания истории. Сцены, объекты и действия можно описывать естественным языком, с последующей трансляцией в `xml`. Это значительно снизит порог вхождения авторов в платформу.

== Плагинная структура

[WARNING]
====
Этот раздел требует обсуждения!
====

В настоящий момент платформа представленна как монолитное приложение без какого либо разделения на модули, его составляющие. Несмотря на логическое разделение проекта на модули (модули-maven), в процессе сборки модули всё равно объединяются в единый jar (для виновс пользователей в exe). Однако возможно использование отдельных подсистем, как самостоятельных модулей (плагинов) в приложении и обновление не целого приложения, а отдельно взятого модуля (например, системы хранения историй для добавления поддержки новых форматов). Более того, возможно помодульное обновление всей платформы без её перезагрузки. Так, например, работает eclipse (правда, из-за особенностей реализации, ему всё равно нужна перезагрузка).
