ЯРИЛ2 Справочник
=================
Язык Разметки Интерактивной Литературы
:doctype: article
:toc: left
:toclevels: 4
:toc-position: left
:toc-title: ЯРИЛ2 - Документация
:numbered:
:icons: font

== Общие сведения
ЯРИЛ -- это платформа для парсерной интерактивной литературы. Платформа состоит из Редактора, Плеера и Тестера.
Игра (история) на ЯРИЛ -- это совокупность сущностей, среди которых:

* Локации
* Предметы
* Действия (команды)
* Процедуры (наборы инструкций для описания реакций на действия и события)
* Признаки (свойства объектов)
* Роли (комплексные свойства объектов)
* Библиотеки (файлы с наборами сущностей)

== Понятия ЯРИЛ
В данном разделе описаны понятия ЯРИЛ, используемые в платформе и данном документе.

=== Идентификатор
Это специальное уникальное имя для объекта ЯРИЛ.

== Сущности ЯРИЛ
=== Локации
Локация -- это отдельная игровая сущность. Подразумевает место в пространстве, содержащее игрока, предметы и персонажей
_(персонажы пока не реализованы но планируются в следующих выпусках)_.

Локация имеет следующие свойства:

* Идентификатор -- см. соответствующее понятие.
* Название -- отображается при описании локации, в том числе при попадании в неё игрока.
* Описание -- описание локации, так же отображается, как и название.
* Переходы -- это ссылки на другие локации. На текущий момент поддерживается 10 переходов: восемь по сторонам света и
два -- вверх и вниз.

=== Действия
Действия -- это сущности ЯРИЛ, являющиеся сопоставлением шаблонов комманд игрока и реацией на них.

== Движок
Движок осуществляет основной игровой процесс (ввод комманды -- обработка).

=== Игровой цикл
Игровой цикл состоит из следующих этапов:

1. Ввод команды игроком.
1. Если команда специальная, то движок её сразу обрабатывает.
1. Распознавание команды парсером.
1. Если команда распознана успешно, то выполняется реакция на неё.
1. Если не успешно -- выводится ошибка или выполняется процедура системного перехвата ошибок парсинга.
1. Движок ожидает ввод следующей команды игроком.

=== Системные перехваты
Движок выполняет игровой цикл, и на его алгоритм нельзя повлиять из игры или библиотеки, но есть места в цикле,
где можно выполнить свою процедуру вместо (или в дополнении к) системной. Вызов таких процедур называется системными
перехватами. Настраивать их для истории (игры) можно, в Редакторе в главном меню
`История -> Перехваты системных процедур...`.

[TIP]
====
Системные перехваты доступны с версии 2015/1.4
====

Перехватываются следующие системные процедуры:

* Вывод описания локации.
* Обработка ошибок парсинга.

Описание этих системных перехватов приведено ниже.

==== Вывод описания локации
Описание текущей локации обычно выводится игроку в двух случаях: когда он ввёл команду "осмотреться" и когда перешёл
в новую локацию. Реакция на команду -- это механизм действий, соответствующее действие "осмотреться" прописано в
системной библиотеке "Глаголы".

...

==== Обработка ошибок парсинга
== Парсер
=== Алгоритм работы парсера
==== Типы фигур блок-схем
==== Основной алгоритм
==== Алгоритм "Сопоставить фразу с шаблоном"
==== Алгоритм "Сопоставить элемент шаблона с началом фразы"
==== Алгоритм "Сопоставить синоним с началом фразы"
==== Алгоритм "Сопоставить слова фразы с объектом"
==== Алгоритм "Убрать из списка подошедших шаблонов недоступные объекты"