---
name: mvn
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
job:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        java: [1.8]
    run-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean install --errors --batch-mode
